version: '3'
services:
   nginx:
      depends_on:
         - api
      restart: always
      build:
         dockerfile: Dockerfile.dev
         context: ./nginx
      ports:
         - "3050:80"
   api:
      depends_on:
         - pg
         - redis
      build:
         dockerfile: Dockerfile.dev
         context: ./api
      ports:
         - "5000:5000"
      environment:
         - PGUSER=postgres
         - PGHOST=pg
         - PGDATABASE=t7api
         - PGPORT=5432
         - REDISCLOUD_URI=redis
      volumes:
         - /app/node_modules
         - ./api:/app
   pg:
      build:
         dockerfile: Dockerfile.dev
         context: ./pg
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_DB=t7api
      volumes:
         - ./pg/data:/var/lib/postgresql/data
   redis:
      image: 'redis:latest'
