version: '3'
services:
   nginx:
      depends_on:
         - api
      restart: always
      build:
         dockerfile: Dockerfile.dev
         context: ./nginx
      ports:
         - "3050:80"
   api:
      depends_on:
         - db
         - redis
      build:
         dockerfile: Dockerfile.dev
         context: ./api
      ports:
         - "5000:5000"
      environment:
         - MONGODB_URI=db
         - REDISCLOUD_URI=redis
      volumes:
         - /app/node_modules
         - ./api:/app
   db:
      build:
         dockerfile: Dockerfile.dev
         context: ./db
      ports:
         - "27017:27017"
      environment:
         - MONGO_INITDB_DATABASE=t7api
      volumes:
         - ./db/data:/data/db
   redis:
      image: 'redis:latest'
